const SET_SELECTED_USER = "SET_SELECTED_USER";
const DELETE_USER = "DELETE_USER";
const ADD_USER = "ADD_USER";
const UPDATE_USER = "UPDATE_USER";

export { SET_SELECTED_USER, DELETE_USER, UPDATE_USER, ADD_USER };
